#!/bin/bash
set -e

echo "Starting Python server..."

pip3 install virtualenv
python3 -m virtualenv venv
source venv/bin/activate
pip3 install -r requirements.txt

# Set your OpenAI API Key as an environment variable
export OPENAI_API_KEY="$1"

# Start the FastAPI app using Uvicorn, an ASGI server
# Replace 'app' with your FastAPI app's module and instance names if different
# For example, if your FastAPI instance is named 'app' in the 'main.py' file, use 'main:app'
uvicorn app:app --reload --host 0.0.0.0 --port 5000 --log-level debug
